// <auto-generated />
namespace MyMedio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Grohbimari : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Grohbimari));
        
        string IMigrationMetadata.Id
        {
            get { return "202410051033252_Grohbimari"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
